#!/bin/bash
echo "-v $HOME/docker-stuff/drools-workbench-showcase/volumes/maven:/opt/jboss/wildfly/bin/repositories/kie/global -v $HOME/docker-stuff/drools-workbench-showcase/volumes/git:/opt/jboss/wildfly/bin/.niogit"
